DROP TABLE IF EXISTS carousels CASCADE;

CREATE TABLE carousels (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  carousel_pic TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
