INSERT INTO dog_media (dog_id, media_picture, media_video, media_description) VALUES
  (1, 'https://placedog.net/640/480?id=31', NULL, 'My sweet furry friend, you brought so much joy and love into my life. I''ll always remember your wagging tail, your wet nose, and your playful energy. You may be gone, but your memory lives on in my heart Furever.'),
  (2, 'https://placedog.net/640/480?id=4', NULL, 'There was nothing better than #CuddleTime with you. You were the perfect lap dog, always snuggling up to us on the couch or in bed. Your warm presence and soft fur were a comfort to us during difficult times. We''ll always cherish the moments we spent together.'),
  (3, 'https://placedog.net/640/480?id=6', NULL, 'You were a master of #TreatsAndTricks. You knew how to sit, stay, shake, and roll over, and you always performed with enthusiasm for a delicious treat. We loved watching you learn and grow, and we miss your eager-to-please spirit.'),
  (4, 'https://placedog.net/640/480?id=30', NULL, 'Every holiday season, you brought so much joy to our family with your wagging tail and playful spirit. Our #HolidayMoments were never complete without you by our side. Your absence is felt deeply, but we''re grateful for the memories we shared together.'),
  (5, 'https://placedog.net/640/480?id=32', NULL, 'Your #FaveToys were always a source of entertainment for us. Whether it was your tennis ball, your squeaky plush toy, or your frisbee, you always had a blast playing with them. We''ll always remember your silly antics and how much joy you brought us.'),
  (1, 'https://placedog.net/640/480?id=2', NULL, 'The house feels empty without you. The sound of your paws on the floor, your bark at the door, and your snuggles on the couch are all memories that I hold close to my heart. Thank you for being such a wonderful friend and for making my life brighter in every way.'),
  (1, 'https://placedog.net/640/480?id=3', NULL, 'Had to repost Buddys profile pic! His #TreatsAndTricks were the highlight of our day. He had a sweet tooth and loved anything with peanut butter, but also knew how to do some pretty impressive tricks, like shaking hands or rolling over. We miss his cute little face and his happy tail wags.'),
  (5, 'https://placedog.net/640/480?id=8', NULL, 'You were the king of #Fetch, always eager to chase after the ball and bring it back to us. We''ll never forget the way you''d trot back with your tail held high and your tongue lolling out. You were a natural athlete and a loyal friend. #FaveToys'),
  (1, 'https://placedog.net/640/480?id=9', NULL, 'Missing my furry companion more than ever today as I reminisce about our summertime swims at the docks. Buddy''s excitement was contagious as we jumped in together. Watching him paddle with grace and ease, his tail wagging with joy, was always a sight to behold. Even though he''s no longer here with me, I still feel his spirit by my side every time I return to the docks. These memories of our time together will always hold a special place in my heart.'),
  (1, 'https://placedog.net/640/480?id=27', NULL, 'You were always by our side, no matter what, and you never let us down. Your #HolidayMoments, #FaveToys, #TreatsAndTricks, and #CuddleTime were just a few of the ways you showed us your love.'),
  (2, 'https://placedog.net/640/480?id=29', NULL, 'Throwback to those carefree days at the beach, playing with my furry friend and his favorite toys. His tail would wag with excitement as I pulled out his favorite ball or frisbee, ready to chase it down and bring it back to me. Watching him run through the surf, his fur glistening in the sunlight, was a sight that always brought a smile to my face. We would play until our tongues hung out, taking breaks to rest in the shade and enjoy the cool breeze. Those moments of pure joy and connection with my pup are memories that I will always treasure. Even though he''s no longer here with me, I can still feel his presence by my side every time I return to the beach. #FaveToys #BeachDays #DogLove #Memories #MissingMyPup');
